# Generated by Django 2.1.3 on 2018-12-12 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFilms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_films',
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='favoritefilms',
            name='fID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Film'),
        ),
        migrations.AddField(
            model_name='favoritefilms',
            name='uID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritefilms',
            unique_together={('uID', 'fID')},
        ),
    ]
