# Generated by Django 2.1.2 on 2018-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_remove_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='user_rating',
            field=models.FloatField(blank=True),
        ),
    ]
