# Generated by Django 2.1.3 on 2018-12-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20181204_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/ketnipz.png', upload_to='avatars'),
        ),
    ]
