# Generated by Django 2.1.3 on 2018-12-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20181204_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/avatars/ketnipz.png', upload_to='static/img/avatars'),
        ),
    ]
