# Generated by Django 2.1.2 on 2018-10-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20181023_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='user_rating',
            field=models.FloatField(default=None),
        ),
    ]
