# Generated by Django 2.1.2 on 2018-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20181023_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='user_rating',
            field=models.FloatField(blank=True),
        ),
    ]
