# Generated by Django 2.1.3 on 2018-12-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20181204_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='img/ketnipz.png', upload_to='img'),
        ),
    ]
