# Generated by Django 2.1.2 on 2018-11-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20181106_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='imdb_rating',
        ),
    ]
