# Generated by Django 2.1.3 on 2018-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20181205_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, default='img/ketnipz.png', upload_to='img'),
        ),
    ]
