# Generated by Django 2.1.3 on 2018-12-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20181205_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
