# Generated by Django 2.1.2 on 2018-12-01 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_film_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
