# Generated by Django 2.1.3 on 2018-12-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_auto_20181205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='user_rating',
            field=models.IntegerField(blank=True),
        ),
    ]
