# Generated by Django 2.1.3 on 2018-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_auto_20181206_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='film',
            name='plot',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
